"""parse date

Revision ID: 0c4d0da8533d
Revises: b7c2ace1ba67
Create Date: 2023-05-30 17:54:08.192634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4d0da8533d'
down_revision = 'b7c2ace1ba67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dramas', sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dramas', 'parse_date')
    # ### end Alembic commands ###
