"""id cache

Revision ID: 25ea8e7ec546
Revises: 0c4d0da8533d
Create Date: 2023-05-30 20:41:35.949529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ea8e7ec546'
down_revision = '0c4d0da8533d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idcache')
    # ### end Alembic commands ###
