"""oops :skull:

Revision ID: 6f777f53813b
Revises: 468fae7965b2
Create Date: 2023-05-26 19:20:31.256156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f777f53813b'
down_revision = '468fae7965b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dramas', sa.Column('known_as', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('dramas', sa.Column('screenwriter', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('director', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('country', sa.String(), nullable=False))
    op.add_column('dramas', sa.Column('episodes', sa.Integer(), nullable=True))
    op.add_column('dramas', sa.Column('aired', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('aired_on', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('release_date', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('original_network', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('content_rating', sa.String(), nullable=True))
    op.add_column('dramas', sa.Column('ranked', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dramas', 'ranked')
    op.drop_column('dramas', 'content_rating')
    op.drop_column('dramas', 'original_network')
    op.drop_column('dramas', 'duration')
    op.drop_column('dramas', 'release_date')
    op.drop_column('dramas', 'aired_on')
    op.drop_column('dramas', 'aired')
    op.drop_column('dramas', 'episodes')
    op.drop_column('dramas', 'country')
    op.drop_column('dramas', 'director')
    op.drop_column('dramas', 'screenwriter')
    op.drop_column('dramas', 'known_as')
    # ### end Alembic commands ###
