"""made dramas, genres, tags unique

Revision ID: 982f11efd402
Revises: 6f777f53813b
Create Date: 2023-05-26 21:45:41.083752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982f11efd402'
down_revision = '6f777f53813b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dramas', ['short_id'])
    op.create_unique_constraint(None, 'genres', ['title'])
    op.create_unique_constraint(None, 'tags', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'dramas', type_='unique')
    # ### end Alembic commands ###
