"""swapped id and year to ints (real)

Revision ID: a343254a3fc2
Revises: b797c8c8ef6c
Create Date: 2023-05-26 22:18:24.764837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a343254a3fc2'
down_revision = 'b797c8c8ef6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dramas', 'short_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='short_id::int')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dramas', 'short_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='short_id::varchar')

    # ### end Alembic commands ###
