"""initial db

Revision ID: b10716af170b
Revises: 
Create Date: 2023-07-04 04:57:01.097335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10716af170b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cinematographer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('native_title', sa.String(), nullable=True),
    sa.Column('known_as', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('screenwriter', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('aired', sa.String(), nullable=True),
    sa.Column('aired_on', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('original_network', sa.String(), nullable=True),
    sa.Column('content_rating', sa.String(), nullable=True),
    sa.Column('ranked', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('screenwriter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('last_online', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contribution_points', sa.String(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('join_date', sa.String(), nullable=False),
    sa.Column('show_watchtime', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('shows', sa.Integer(), nullable=True),
    sa.Column('movie_watchtime', sa.String(), nullable=True),
    sa.Column('movies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_drama',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'drama_id')
    )
    op.create_table('cinematographer_drama',
    sa.Column('cinematographer_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinematographer_id'], ['cinematographer.id'], ),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.PrimaryKeyConstraint('cinematographer_id', 'drama_id')
    )
    op.create_table('composer_drama',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.PrimaryKeyConstraint('composer_id', 'drama_id')
    )
    op.create_table('director_drama',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.PrimaryKeyConstraint('director_id', 'drama_id')
    )
    op.create_table('drama_genre',
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('drama_id', 'genre_id')
    )
    op.create_table('drama_tag',
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('drama_id', 'tag_id')
    )
    op.create_table('screenwriter_drama',
    sa.Column('screenwriter_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['screenwriter_id'], ['screenwriter.id'], ),
    sa.PrimaryKeyConstraint('screenwriter_id', 'drama_id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completed',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'drama_id')
    )
    op.create_table('currently_watching',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'drama_id')
    )
    op.create_table('dropped',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'drama_id')
    )
    op.create_table('on_hold',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'drama_id')
    )
    op.create_table('plan_to_watch',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'drama_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_to_watch')
    op.drop_table('on_hold')
    op.drop_table('dropped')
    op.drop_table('currently_watching')
    op.drop_table('completed')
    op.drop_table('watchlist')
    op.drop_table('screenwriter_drama')
    op.drop_table('drama_tag')
    op.drop_table('drama_genre')
    op.drop_table('director_drama')
    op.drop_table('composer_drama')
    op.drop_table('cinematographer_drama')
    op.drop_table('actor_drama')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('screenwriter')
    op.drop_table('idcache')
    op.drop_table('genre')
    op.drop_table('drama')
    op.drop_table('director')
    op.drop_table('composer')
    op.drop_table('cinematographer')
    op.drop_table('actor')
    # ### end Alembic commands ###
