"""swapped id and year to ints

Revision ID: b797c8c8ef6c
Revises: 982f11efd402
Create Date: 2023-05-26 22:15:36.917005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b797c8c8ef6c'
down_revision = '982f11efd402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
