"""initial db

Revision ID: c8e457e119f3
Revises: 
Create Date: 2023-06-29 22:12:09.321513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e457e119f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('full_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('native_title', sa.String(), nullable=True),
    sa.Column('known_as', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('screenwriter', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('aired', sa.String(), nullable=True),
    sa.Column('aired_on', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('original_network', sa.String(), nullable=True),
    sa.Column('content_rating', sa.String(), nullable=True),
    sa.Column('ranked', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parse_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('last_online', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contribution_points', sa.String(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('join_date', sa.String(), nullable=False),
    sa.Column('show_watchtime', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('shows', sa.Integer(), nullable=True),
    sa.Column('movie_watchtime', sa.String(), nullable=True),
    sa.Column('movies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drama_genre',
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('drama_id', 'genre_id')
    )
    op.create_table('drama_tag',
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('drama_id', 'tag_id')
    )
    op.create_table('drama_user',
    sa.Column('drama_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('currently_watching', 'completed', 'plan_to_watch', 'on_hold', 'dropped', name='watchlisttype'), nullable=True),
    sa.ForeignKeyConstraint(['drama_id'], ['drama.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('drama_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drama_user')
    op.drop_table('drama_tag')
    op.drop_table('drama_genre')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('idcache')
    op.drop_table('genre')
    op.drop_table('drama')
    # ### end Alembic commands ###
