"""huh

Revision ID: cfb6964b2431
Revises: 7aea02f21a46
Create Date: 2023-06-21 14:24:11.666875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb6964b2431'
down_revision = '7aea02f21a46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
